version: '3.9'
services:
  test:
    build: .
    image: openai-server:latest
    restart: always
    ports:
      - 5900:5900
      - 3000:3000
    volumes:
      - ./src:/app/src
    extra_hosts:
      - "master.io:192.168.0.230"
